default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "default_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "default_password") %>
  host: localhost
  
development:
  <<: *default
  database: notebook_api_development

test:
  <<: *default
  database: notebook_api_test

production:
  primary:
    <<: *default
    database: notebook_api_production
  cache:
    <<: *default
    database: notebook_api_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: notebook_api_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: notebook_api_production
    migrations_paths: db/cable_migrate
