default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 784512mbl
  host: localhost

development:
  <<: *default
  database: notebook_api_development

test:
  <<: *default
  database: notebook_api_test

production:
  primary:
    <<: *default
    database: notebook_api_production
  cache:
    <<: *default
    database: notebook_api_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: notebook_api_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: notebook_api_production
    migrations_paths: db/cable_migrate
